import { legacyCat as cat } from './legacy-links';

/**
 * Editorial content of the Pool & Spa Filters category page (legacy Pool-Spa-Filters-cat.asp,
 * the April 2026 "ff-ps" redesign): finder tabs, brand logos, helper copy, the D.E. banner,
 * the three content bands and the FAQ. Hard-coded on the live site too.
 */
export const POOL_CATEGORY_SLUG = 'pool-spa-filters';
const IMG = 'https://www.filtersfast.com/images';
const ASSET = `${IMG}/FiltersFast_2026_FF-A-PoolAndSpa-Redesign-April2026_`;

export const POOL_HERO = {
  heading: 'Find Your Pool Filter',
  sub: "Search by brand, part number, or filter dimensions — we'll help you find the replacement you need",
  icons: { brand: `${ASSET}by-brand.svg`, part: `${ASSET}part-number.svg`, dimensions: `${ASSET}dimensions.svg`, step: `${ASSET}step-one.svg`, info: `${ASSET}info-icon.svg`, de: `${ASSET}de-icon.svg` },
  partHelp: { title: 'Where to find your part number', text: "It's printed on the label on the end cap of your existing filter cartridge. Part numbers usually start with letters then numbers — e.g. C-7468, PA106, FC-1220, PRB50-IN." },
  measureHelp: { title: 'How to Measure', text: 'Measure your existing cartridge with end caps on. Length = top to bottom. Diameter = widest point across the middle.' },
};

export const POOL_BRANDS: { name: string; href: string; logo: string }[] = [
  { name: 'Hayward', href: cat('Hayward-Waterway-Pool-and-Spa-Filters-cat.asp'), logo: `${IMG}/FF-Hayward-Logo-2x.png` },
  { name: 'Pentair', href: cat('Pentair-Pool-And-Spa-cat.asp'), logo: `${IMG}/FF-Pentair-Logo-2x.png` },
  { name: 'Intex', href: cat('Intex-Pool-and-Spa-Filters-cat.asp'), logo: `${IMG}/intex-recreation-corp-logo-vector.png` },
  { name: 'Waterway', href: cat('waterway-pool-spa-filters-cat.asp'), logo: `${IMG}/waterway_plastics_logo.jpg` },
  { name: 'Jandy', href: cat('Jandy-Pool-and-Spa-Filters-cat.asp'), logo: `${IMG}/jandylogo.jpg` },
  { name: 'Sta-Rite', href: cat('Sta-Rite-Pool-and-Spa-Filters-cat.asp'), logo: `${IMG}/sta-rite_logo.jpg` },
  { name: 'Pleatco', href: cat('comp-replacement-pool-spa-filters-cat.asp'), logo: `${IMG}/Pleatco-Logo-Ace.png` },
  { name: 'Filbur', href: cat('Filbur-Pool-Spa-Filters-cat.asp'), logo: `${IMG}/filbur-logo-trinity.png` },
];

export const POOL_DE = { heading: 'Need a D.E. Pool Filter?', text: 'Browse our full selection of diatomaceous earth filters, built for crystal-clear results.', cta: 'Shop D.E. Filters', legacy: 'diatomaceous-earth-filters-cat.asp' };

export const POOL_BANDS: { tone: 'dark' | 'light'; heading: string; html: string; image: string; mobileImage: string; alt: string }[] = [
  { tone: 'dark', heading: 'High Quality Pool Filters and Replacements', image: `${ASSET}d-high-quality.webp`, mobileImage: `${ASSET}m-high-quality.webp`, alt: 'Family enjoying a swimming pool', html: "<p>Clear pool water begins and ends with the right filtration, and there's no better way to find the best pool filters than to shop at Filters Fast. The right pool filter replacement plays a critical role in keeping debris, contaminants, and fine particles out of your swimming water, which helps you maintain a cleaner, safer pool environment from day to day. Filters Fast simplifies the process with a trusted selection of pool filters and replacements designed for reliable system compatibility. With the right pool filters working hard behind the scenes, all you have to do is relax and enjoy your clear, sparkling water.</p>" },
  { tone: 'light', heading: 'Why Choose Filters Fast for Pool Filter Replacements', image: `${ASSET}d-why-choose.webp`, mobileImage: `${ASSET}m-why-choose.webp`, alt: 'Person relaxing in a swimming pool', html: "<p>For more than 20 years, Filters Fast has been a trusted source for high-quality pool filtration solutions. Because you deserve options that meet your exact system requirements, we're proud to offer a wide range of products designed to fit all major brands. Our carefully curated selection ensures reliable performance, and our expert support team is always available to answer questions and guide you to the right solution. With fast shipping, competitive pricing, easy-to-use search tools, and our convenient <a href=\"/home-filter-club\">auto delivery options</a>, Filters Fast makes finding the right pool filter replacement simple, quick, and worry-free.</p>" },
  { tone: 'dark', heading: 'Maintain Clean and Safe Pool Water with Proper Filtration', image: `${ASSET}d-maintain-clean.webp`, mobileImage: `${ASSET}m-maintain-clean.webp`, alt: 'People enjoying clean water', html: `<p>Regular pool filter maintenance is key to protecting your equipment and extending its lifespan. Swapping out your filter on schedule helps your system run efficiently, prevents clogs, and keeps water circulating properly. Filters Fast makes it easy to stay on top of replacements with a wide selection of high-quality filters designed for all major pool systems. Compare options, choose the right fit, shop our site for the <a href="${cat('overstock-items-cat.asp')}">best offer</a>, and set up auto delivery so you never miss a replacement. With the right pool filter in place, you can focus on enjoying your pool without a single worry about water quality.</p>` },
];

export const POOL_FAQ_IMAGE = `${ASSET}d-pool-spa-FAQ.webp`;
export const POOL_FAQS: { q: string; a: string }[] = [
  { q: 'How often should I replace my pool filter cartridge?', a: "<p>Pool filter cartridges typically need to be replaced every 1 to 2 years, but your filter's lifespan will depend on usage, water quality, and the type of pool system you have. Signs that it's time for a swimming pool filter replacement include reduced water flow, cloudy water, or visible wear and tear on the cartridge itself. Regularly inspecting and cleaning your cartridge between replacements can help extend its lifespan and keep your pool water clean and clear.</p>" },
  { q: 'What are the three main types of pool filters, and which is right for me?', a: "<p>Choosing the right pool filter depends on your water clarity needs, maintenance preferences, and budget. Let's take a look at the three most common types and some of their key features:</p><p><strong>Sand Filters</strong></p><ul><li>Trap debris using a bed of specially graded sand</li><li>Water flows through the sand to capture dirt and particles</li><li>Easy to maintain with simple backwashing and relatively low upfront cost</li></ul><p><strong>Cartridge Filters</strong></p><ul><li>Capture contaminants with a pleated fabric cartridge</li><li>Require less water for cleaning - simply remove and rinse with a hose</li><li>Provide finer filtration than sand, often catching particles as small as 10 to 15 microns</li></ul><p><strong>Diatomaceous Earth (DE) Filters</strong></p><ul><li>Use fossilized diatom powder coated onto internal grids</li><li>Deliver the finest filtration, removing particles as small as 2 to 5 microns</li><li>Require more maintenance and a higher initial investment, but produce exceptionally clear water</li></ul><p>No matter your pool size or type, Filters Fast carries high-quality replacements that make it easy to keep your pool water pristine.</p>" },
  { q: 'How do I know if my pool filter needs replacing?', a: "<p>Common signs that it's time to replace your pool water filter include cloudy or dirty water, reduced water flow, visible buildup on the filter itself, or visibly worn filter media. You might notice other indicators that your filter is no longer performing at its best, including longer filtration times, increased chemical use, or unusual odors. Regularly replacing your filter keeps your pool clean, your system running efficiently, and your swimming water safe and inviting. Filters Fast makes staying on schedule easy with the <a href=\"/home-filter-club\">Home Filter Club</a> - a subscription program that delivers your pool filter replacements automatically so you never have to worry about poor water quality.</p>" },
  { q: 'How do I know what size pool filter I need?', a: "<p>Choosing the right pool filter starts with checking your existing filter for the model or part number, which makes finding a compatible replacement much easier. You'll also need to consider your pool's size and flow rate. Larger pools require higher-capacity filters, while smaller pools or spas may need compact systems. Water quality matters, too, because pools with heavy debris, frequent use, or hard water may need filters that handle extra particles. By combining these factors and shopping at Filters Fast, you can find a filter that keeps your pool or spa clean and your system running efficiently.</p>" },
  { q: "How do I match a filter to my pump's flow rate?", a: "<p>Your pool filter will work best when it matches your pump's flow rate. Check your pump's specifications for gallons per minute (GPM) or gallons per hour (GPH) and pick a filter that's rated for that capacity. The right match prevents strain on your pump, keeps water circulating properly, and helps your filter capture debris efficiently so your pool stays clean and sparkling.</p>" },
  { q: 'What is backwashing, and which filters require it?', a: "<p>Backwashing is a process that reverses the flow of water through your pool filter to flush out trapped debris. It's basically a very effective, simple way to clean your pool filter. Sand filters and DE filters typically require backwashing, while pool cartridge filters generally do not. When you backwash your filter as recommended, you help maintain proper water flow, prolong filter life, and keep your pool sparkling clean.</p>" },
  { q: 'Why should I choose Filters Fast® pool filter cartridge over other brands?', a: "<p>Filters Fast® pool filter cartridges offer dependable performance at a price that makes sense. Each filter is carefully designed to fit major pool systems, deliver effective filtration, and ensure consistent water clarity. With the <a href=\"/support\">Filters Fast support center</a> available to answer questions and guide you to the right replacement, you can shop with confidence knowing you're getting quality, compatibility, and value all in one.</p>" },
];
