-- 01-products: master product export (all rows, including inactive/discontinued; the importer filters).
-- Column names inferred from Manager/SA_prod_exec.asp, SA_prod_edit.asp and prodViewHv2.asp.
-- If a column errors as unknown, remove it and rename the output file to note it.
SET NOCOUNT ON;
SELECT
  p.idProduct,
  p.sku,
  p.manufacturesku,
  p.manufacture,
  p.description,
  p.descriptionLong,
  CAST(p.details AS nvarchar(max)) AS details,
  p.relatedKeys,
  p.price,
  p.listPrice,
  p.cgs,
  p.MAP,
  p.ogPrice,
  p.weight,
  p.dimFee,
  p.stock,
  p.ignoreStock,
  p.actualInventory,
  p.leadTime,
  p.dropShip,
  p.delayedShipmentFlag,
  p.blockedReason,
  p.active,
  p.hotDeal,
  p.homePage,
  p.poprank,
  p.pagename,
  p.imageURL,
  p.smallImageURL,
  p.imageURL2Pack,
  p.imageURL3Pack,
  p.guaranteeBadge,
  p.metatitle,
  p.metadesc,
  p.metakey,
  p.noShipCharge,
  p.discountedShipping,
  p.srcFreeShip,
  p.taxExempt,
  p.freeproduct,
  p.giftwithpurchase,
  p.AutoShipEnabled,
  p.recommendedfrequency,
  p.RecommendedProd,
  p.recommendOnly,
  p.related1, p.related2, p.related3,
  p.CompareTo,
  p.compareToAlt,
  p.CompareToSortOrder,
  p.compareDefaultOption,
  p.familyDesignation,
  p.privateLabel,
  p.packMultFlag,
  p.packSizeUOM,
  p.packSize,
  p.maxCartQty,
  p.showPriceInCart,
  p.feedoverride,
  p.includeInFeed,
  p.googleActionsEnabled,
  p.googleActionsPrice,
  p.googleMinAutoDisc,
  p.wpNotAff,
  p.retExclude,
  p.prop65,
  p.madeInUSA,
  p.upc,
  p.upcn,
  p.reviewAllow,
  p.reviewAutoActive,
  p.idPaired,
  p.discontinuedAlternative,
  p.discontinuedAltType,
  p.discontinuedText,
  p.tempUnavailableAlternative,
  p.tempUnavailableText,
  p.fridgeFilter,
  p.ffAirFilter,
  p.ffWaterFilter,
  p.humidifierFilter,
  p.homeAirFilter,
  pscd.siteSearchDisable,
  CAST(pscd.Details AS nvarchar(max)) AS searchCompDetails
FROM products p
LEFT JOIN ProductSearchCompDetails pscd ON pscd.Id = p.idProduct
ORDER BY p.idProduct;
