/**
 * Builds packages/db/seed/seed.sql from the legacy search-feed exports
 * (FiltersFast/srchupload/*.txt). This gives the dev database a real
 * catalog (~12.8k products, ~1k categories, ~83k appliance models) without
 * SQL Server access. Columns the feeds don't carry (options, specs, model→product
 * links, parent categories) arrive later from the SQL export pack in
 * docs/DATA-EXPORT.md.
 *
 * Usage:  pnpm --filter @ff/db seed:build [--src <path-to-srchupload>]
 */
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const argSrc = process.argv.indexOf('--src');
const SRC = resolve(
  argSrc > -1 ? process.argv[argSrc + 1]! : process.env.FF_LEGACY_FEEDS ?? 'C:/Users/adam/source/repos/FiltersFast/srchupload',
);
const OUT_DIR = join(here, 'chunks');
/** wrangler's local D1 runner runs out of memory on one 20 MB file, so emit ~1.5 MB chunks. */
const CHUNK_BYTES = 1_500_000;
const LEGACY_IMAGE_HOST = 'https://www.filtersfast.com';

// ---------- helpers ----------
function readTsv(file: string): Record<string, string>[] {
  const raw = readFileSync(join(SRC, file), 'utf8').replace(/^\uFEFF/, '');
  const lines = raw.split(/\r?\n/).filter((l) => l.length > 0);
  const header = lines[0]!.split('\t').map((h) => h.trim());
  return lines.slice(1).map((line) => {
    const cells = line.split('\t');
    const row: Record<string, string> = {};
    header.forEach((h, i) => (row[h] = (cells[i] ?? '').trim()));
    return row;
  });
}

function q(v: string | number | null | undefined): string {
  if (v === null || v === undefined || v === '') return 'NULL';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
  return `'${v.replace(/'/g, "''")}'`;
}

function slugify(input: string): string {
  return input
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function toCents(s: string): number | null {
  const n = Number.parseFloat(s.replace(/[$,]/g, ''));
  return Number.isFinite(n) ? Math.round(n * 100) : null;
}

function normalizeModel(m: string): string {
  return m
    .toUpperCase()
    .replace(/[-\s/\\_$!#%*+@^&=.()'"]/g, '')
    .replace(/O|Q/g, '0')
    .replace(/B/g, '8')
    .replace(/S/g, '5')
    .replace(/I|L/g, '1');
}

function legacyImage(url: string): string | null {
  if (!url) return null;
  const m = url.match(/\/ProdImages\/(.+)$/i);
  return m ? `${LEGACY_IMAGE_HOST}/ProdImages/${m[1]}` : url;
}

function legacyPagename(link: string): string | null {
  try {
    const u = new URL(link);
    return decodeURIComponent(u.pathname.replace(/^\//, ''));
  } catch {
    return null;
  }
}

/** D1 caps a single statement at 100 KB, so batches are sized by bytes, not rows. */
function insertBatches(table: string, columns: string[], rows: string[][], maxBytes = 80_000): string[] {
  const out: string[] = [];
  const head = `INSERT OR REPLACE INTO ${table} (${columns.join(',')}) VALUES\n`;
  let chunk: string[] = [];
  let size = head.length;
  const flush = () => {
    if (chunk.length) out.push(head + chunk.join(',\n') + ';');
    chunk = [];
    size = head.length;
  };
  for (const r of rows) {
    const v = `(${r.join(',')})`;
    if (size + v.length + 2 > maxBytes) flush();
    chunk.push(v);
    size += v.length + 2;
  }
  flush();
  return out;
}

// ---------- load ----------
const products = readTsv('prodgen.txt');
const categories = readTsv('categories.txt');
const catProducts = readTsv('categories_products.txt');
const models = readTsv('keyword-url.txt');

const sql: string[] = [
  '-- Generated by packages/db/seed/build-seed.ts. Do not edit by hand.',
  'PRAGMA foreign_keys = OFF;',
  'DELETE FROM category_products;',
  'DELETE FROM model_products;',
  'DELETE FROM products;',
  'DELETE FROM categories;',
  'DELETE FROM brands;',
  'DELETE FROM appliance_models;',
];

// brands
const brandNames = new Map<string, number>();
let brandId = 0;
for (const p of products) {
  const name = p['Mfr']?.trim();
  if (name && !brandNames.has(name)) brandNames.set(name, ++brandId);
}
const usedBrandSlugs = new Set<string>();
const brandRows = [...brandNames.entries()].map(([name, id]) => {
  let slug = slugify(name) || `brand-${id}`;
  if (usedBrandSlugs.has(slug)) slug = `${slug}-${id}`;
  usedBrandSlugs.add(slug);
  return [q(id), q(name), q(slug), '1'];
});
sql.push(...insertBatches('brands', ['id', 'name', 'slug', 'active'], brandRows));

// categories
const usedCatSlugs = new Set<string>();
const categoryRows = categories
  .filter((c) => c['idcategory'])
  .map((c) => {
    const id = Number(c['idcategory']);
    const pagname = c['pagname'] ?? '';
    let slug = pagname ? slugify(pagname.replace(/-cat\.asp$/i, '').replace(/\.asp$/i, '')) : slugify(c['categorydesc'] ?? '');
    if (!slug) slug = `category-${id}`;
    if (usedCatSlugs.has(slug)) slug = `${slug}-${id}`;
    usedCatSlugs.add(slug);
    const kind = c['cattype'] ? Number(c['cattype']) : null;
    const html = (c['categoryhtml'] ?? '').replace(/<br\s*\/?>/gi, '').trim();
    return [q(id), q(c['categorydesc'] ?? ''), q(html || null), q(slug), q(pagname || null), q(kind), pagname ? '1' : '0'];
  });
sql.push(...insertBatches('categories', ['id', 'name', 'h1', 'slug', 'legacy_slug', 'kind', 'active'], categoryRows));

// products
const usedProdSlugs = new Set<string>();
const productIds = new Set<number>();
const productRows = products.map((p) => {
  const id = Number(p['IDproduct']);
  productIds.add(id);
  const pagename = legacyPagename(p['Link'] ?? '') ?? '';
  let slug = pagename ? slugify(pagename.replace(/\.asp(\?.*)?$/i, '').replace(/^p-/i, '')) : slugify(p['Title'] ?? '');
  if (!slug) slug = `product-${id}`;
  if (usedProdSlugs.has(slug)) slug = `${slug}-${id}`;
  usedProdSlugs.add(slug);
  const stock = Number.parseInt(p['Stock1'] ?? '0', 10);
  const price = toCents(p['Price'] ?? '') ?? 0;
  const list = toCents(p['List Price'] ?? '');
  const asLowAs = toCents(p['aslowasprice'] ?? '');
  const brand = p['Mfr']?.trim() ?? '';
  const privateLabel = /^(filters ?fast|pureh2o)/i.test(brand);
  return [
    q(id),
    q(p['SKU'] ?? ''),
    q(p['Title'] ?? ''),
    q(slug),
    q(pagename.replace(/\?.*$/, '') || null),
    q(brandNames.get(brand) ?? null),
    q(brand || null),
    q(p['Description'] || null),
    q(price),
    q(list && list > price ? list : null),
    q(asLowAs && asLowAs < price ? asLowAs : null),
    q(legacyImage(p['Image'] ?? '')),
    q(legacyImage(p['Small Image URL'] ?? '')),
    q(Number.isFinite(stock) ? stock : 0),
    p['freeshipping'] === 'Y' ? '1' : '0',
    privateLabel ? '1' : '0',
    q(Number.parseInt(p['poprank'] ?? '9999', 10) || 9999),
    stock === -250 ? '0' : '1',
  ];
});
sql.push(
  ...insertBatches(
    'products',
    [
      'id', 'sku', 'name', 'slug', 'legacy_slug', 'brand_id', 'brand_name', 'description_html',
      'price_cents', 'list_price_cents', 'as_low_as_cents', 'image_url', 'thumb_url', 'stock',
      'free_shipping', 'private_label', 'pop_rank', 'active',
    ],
    productRows,
  ),
);

// category_products
const catIds = new Set(categoryRows.map((r) => Number(r[0])));
const cpSeen = new Set<string>();
const cpRows: string[][] = [];
for (const cp of catProducts) {
  const pid = Number(cp['idProduct']);
  const cid = Number(cp['idCategory']);
  const key = `${cid}:${pid}`;
  if (!productIds.has(pid) || !catIds.has(cid) || cpSeen.has(key)) continue;
  cpSeen.add(key);
  cpRows.push([q(cid), q(pid), '0']);
}
sql.push(...insertBatches('category_products', ['category_id', 'product_id', 'sort_order'], cpRows));

// appliance models
const modelSeen = new Set<string>();
const modelRows: string[][] = [];
for (const m of models) {
  const number = (m['Model Number'] ?? '').trim();
  if (!number || modelSeen.has(number.toUpperCase())) continue;
  modelSeen.add(number.toUpperCase());
  modelRows.push([q(number), q(normalizeModel(number)), q(m['Manufacturer'] || null)]);
}
sql.push(...insertBatches('appliance_models', ['model_number', 'normalized', 'brand_name'], modelRows));

sql.push('PRAGMA foreign_keys = ON;');

rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });
let chunk: string[] = [];
let bytes = 0;
let files = 0;
const flushChunk = () => {
  if (!chunk.length) return;
  writeFileSync(join(OUT_DIR, `seed-${String(files++).padStart(3, '0')}.sql`), chunk.join('\n\n') + '\n', 'utf8');
  chunk = [];
  bytes = 0;
};
for (const stmt of sql) {
  if (bytes + stmt.length > CHUNK_BYTES) flushChunk();
  chunk.push(stmt);
  bytes += stmt.length;
}
flushChunk();

console.log(
  `${files} seed chunks written to ${OUT_DIR}: ${brandRows.length} brands, ${categoryRows.length} categories, ${productRows.length} products, ${cpRows.length} category links, ${modelRows.length} models`,
);
