/// <reference types="astro/client" />

// Bindings (DB, SESSION, CACHE, IMAGES, ...) are typed in worker-configuration.d.ts,
// generated by `pnpm cf-typegen` (wrangler types) from wrangler.jsonc.
// Access them at runtime with:  import { env } from 'cloudflare:workers'

declare namespace App {
  interface Locals {
    /** Cloudflare request geo, filled in by middleware from cf headers. */
    geo: {
      country: string;
      region?: string;
      city?: string;
    };
    /** Signed-in customer (Better Auth), or null. Never set on /manager routes. */
    user: { id: string; email: string; name: string; customerId: number | null } | null;
    session: { id: string; expiresAt: Date } | null;
    /** Signed-in back-office admin (own table + cookie), only ever set on /manager routes. */
    admin: { id: number; email: string; name: string | null; mustChangePassword: boolean } | null;
  }
}
