/// <reference types="astro/client" />

// Bindings (DB, SESSION, CACHE, IMAGES, ...) are typed in worker-configuration.d.ts,
// generated by `pnpm cf-typegen` (wrangler types) from wrangler.jsonc.
// Access them at runtime with:  import { env } from 'cloudflare:workers'

declare namespace App {
  interface Locals {
    /** Cloudflare request geo, filled in by middleware from cf headers. */
    geo: {
      country: string;
      region?: string;
      city?: string;
    };
  }
}
